Babys's first concept.
The errors actually ARE easier to read. Sure, it's a lot of words in
this training-wheels case.

gpsbabel/garmin_txt.cc:974:22: error: no matching function for call to 'FahrenheitToCelsius'
      *temperature = FahrenheitToCelsius("booger");
                     ^~~~~~~~~~~~~~~~~~~
gpsbabel/defs.h:92:3: note: candidate template ignored: constraints not satisfied [with T = const char *]
T FahrenheitToCelsius(T a) { return (a - 32.0) / 1.8;}
  ^
gpsbabel/defs.h:91:10: note: because 'const char *' does not satisfy 'integral'
requires std::integral<T> || std::floating_point<T>
         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__concepts/arithmetic.h:30:20: note: because 'is_integral_v<const char *>' evaluated to false
concept integral = is_integral_v<_Tp>;
                   ^
gpsbabel/defs.h:91:30: note: and 'const char *' does not satisfy 'floating_point'
requires std::integral<T> || std::floating_point<T>
                             ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/c++/v1/__concepts/arithmetic.h:39:26: note: because 'is_floating_point_v<const char *>' evaluated to false
concept floating_point = is_floating_point_v<_Tp>;